version: '3'

services:
  portainer:
    container_name: portainer
    restart: unless-stopped
    image: portainer/portainer
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      VIRTUAL_HOST: service.portainer.kornkawin.dev
      LETSENCRYPT_HOST: service.portainer.kornkawin.dev

    ports:
      - "9000"

volumes: 
  portainer_data:

networks:
  default:
    external:
      name: webproxy
