version: '3'

services:
  register:
    container_name: register_gateway
    build: python/
    restart: always
    environment:
      VIRTUAL_HOST: www.api.kornkawin.dev
    ports:
      - "7001:80"
networks:
  default:
    external:
      name: microservice_network
